[tool.black]
target-version = ['py35', 'py36', 'py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | tensorflow_addons/activations/rrelu.py
  | tensorflow_addons/activations/rrelu_test.py
  | tensorflow_addons/image/filters.py
  | tensorflow_addons/image/filters_test.py
  | tensorflow_addons/layers/normalizations.py
  | tensorflow_addons/layers/normalizations_test.py
  | tensorflow_addons/layers/wrappers.py
  | tensorflow_addons/layers/wrappers_test.py
  | tensorflow_addons/losses/__init__.py
  | tensorflow_addons/losses/focal_loss.py
  | tensorflow_addons/losses/giou_loss.py
  | tensorflow_addons/losses/giou_loss_test.py
  | tensorflow_addons/metrics/cohens_kappa.py
  | tensorflow_addons/metrics/cohens_kappa_test.py
  | tensorflow_addons/metrics/matthews_correlation_coefficient.py
  | tensorflow_addons/metrics/multilabel_confusion_matrix.py
  | tensorflow_addons/metrics/r_square.py
  | tensorflow_addons/optimizers/__init__.py
  | tensorflow_addons/optimizers/lookahead.py
  | tensorflow_addons/optimizers/lookahead_test.py
  | tensorflow_addons/optimizers/moving_average.py
  | tensorflow_addons/optimizers/moving_average_test.py
  | tensorflow_addons/optimizers/weight_decay_optimizers.py
  | tensorflow_addons/optimizers/weight_decay_optimizers_test.py
  | tensorflow_addons/rnn/cell.py
  | tensorflow_addons/rnn/cell_test.py
  | tensorflow_addons/seq2seq/attention_wrapper_test.py
  | tensorflow_addons/text/__init__.py
  | tensorflow_addons/text/crf.py
  | tensorflow_addons/text/crf_test.py
  | tensorflow_addons/image/distance_transform_test.py
  | tensorflow_addons/optimizers/lazy_adam_test.py
)
'''
