name: Notify codeowners

on:
  pull_request_target:
    types: [opened]


permissions:
  contents: read

jobs:
  notify-codeowners:
    name: Notify codeowners
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: pip install pygithub click
      - name: Drop a message for codeowners
        env:
          PR: ${{ steps.findPr.outputs.pr }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python .github/workflows/notify_codeowners.py \
              --pull-request-id=auto \
              --no-dry-run
