name: Validate codeowners

on:
  push:
    branches:
      - master
      - r*

#  pull_request_target:
#    branches:
#      - master
#      - r*
# Enable pull_request_target when notify_codeowners.py can validate the codeowners file
# of the commit that triggered the workflow, not the commit the workflow is runnng on.
# Otherwise, it's useless, it just check the codeowners file from the latest commit in master


permissions:
  contents: read

jobs:
  validate-codeowners:
    name: Check that the CODEOWNERS is valid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: pip install pygithub click
      - name: Check that the CODEOWNERS is valid
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python .github/workflows/notify_codeowners.py